# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cobweb\SvconnectorConerstone\:
    resource: '../Classes/*'

  Cobweb\SvconnectorCornerstone\Service\ConnectorJson:
    public: true
    arguments:
      - !tagged_iterator connector.service
